### ISSUE TITLE
Update 0.147.3 won't let me connect 

### ISSUE THREAD

**Issue by ottobaer** [AlexMog/Longship#25] opened 2021-03-02 10:34 UTC
Hi, 

After the latest update I can't connect to a server that has longship installed. I just get a message saying disconnected after a while. 
I tried it with an unmodded server and it works without problems.

**Comment by AlexMog** [comment] 2021-03-02 10:37
Hello,
Did you get any error messages in your server console ?

**Comment by ottobaer** [comment] 2021-03-02 10:43
I get a lot of messages like that - don't know if that is an error. 
```

Found UnityPlayer, hooking into it instead
Found path: /home/steam/valheim/valheim_server.x86_64
Mono path[0] = '/home/steam/valheim/valheim_server_Data/Managed'
Mono config path = '/home/steam/valheim/valheim_server_Data/MonoBleedingEdge/etc'
Got override: /home/steam/valheim/unstripped_corlib
Current root dir: /home/steam/valheim/valheim_server_Data/Managed
New root path: /home/steam/valheim/unstripped_corlib
Search path: /home/steam/valheim/unstripped_corlib:/home/steam/valheim/valheim_server_Data/Managed
Setting config paths; basedir: /home/steam/valheim; config: /home/steam/valheim/valheim_server.x86_64.config
Managed dir: /home/steam/valheim/valheim_server_Data/Managed
Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/<90>^N<FB><9E><EC>U/mono/aot-cache/amd64/BepInEx.Preloader.dll.so
Got image: 0x55ec9efb10f0
Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/BepInEx.dll.so
Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/System.Core.dll.so
Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/System.Configuration.dll.so
Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/System.Xml.dll.so
Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/data-0x7f6418835010.so
Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/data-0x7f6418835010.so
Preloaded 'libsteam_api.so'
Initialize engine version: 2019.4.20f1 (6dd1c08eedfa)
[Subsystems] Discovering subsystems at path /home/steam/valheim/valheim_server_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly

```

And  a lot of these : 
```

Load DLL: /home/steam/valheim/valheim_server_Data/Managed/UnityEngine.dll
Base: UnityEngine.dll
Redirecting to /home/steam/valheim/unstripped_corlib/UnityEngine.dll
Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/UnityEngine.dll.so
Load DLL: /home/steam/valheim/valheim_server_Data/Managed/UnityEngine.AIModule.dll
Base: UnityEngine.AIModule.dll
Redirecting to /home/steam/valheim/unstripped_corlib/UnityEngine.AIModule.dll
Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/UnityEngine.AIModule.dll.so
Load DLL: /home/steam/valheim/valheim_server_Data/Managed/UnityEngine.AndroidJNIModule.dll
Base: UnityEngine.AndroidJNIModule.dll
Redirecting to /home/steam/valheim/unstripped_corlib/UnityEngine.AndroidJNIModule.dll
Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/UnityEngine.AndroidJNIModule.dll.so
Load DLL: /home/steam/valheim/valheim_server_Data/Managed/UnityEngine.AnimationModule.dll

```

Then it seems to load the Plugin : 

```

- Completed reload, in  0.029 seconds
UnloadTime: 0.718041 ms
[Message:   BepInEx] BepInEx 5.4.6.0 - valheim_server
[Info   :   BepInEx] Running under Unity vUnknown (post-2017)
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Linux
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Info   :   BepInEx] Detected Unity version: v2019.4.20f1
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [Longship 0.1.7]
Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/Longship.dll.so
[Info   :  Longship] Starting v0.1.7...
[Info   :  Longship] Checking for updates...
Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/UnityEngine.JSONSerializeModule.dll.so
[Info   :  Longship] Loading server configuration...
[Info   :  Longship] Loading plugins...
[Info   :  Longship] Ready.
[Message:   BepInEx] Chainloader startup complete
03/02/2021 11:24:55: Starting to load scene:start

```

Maybe this in an error ? 


```


MissingMethodException: void ZNet.SetServerHost(string,int)
  at (wrapper dynamic-method) FejdStartup.DMD<FejdStartup::ParseServerArguments>(FejdStartup)
  at FejdStartup.Awake () [0x000f0] in <bf9bd142b7c04f32b4e15d64d8018201>:0

```

**Comment by AlexMog** [comment] 2021-03-02 10:50
The last one is the error I was looking for !
It seems like Valheim has updated recently and some method signatures have changed. I'll update that later today and provide a new release for this new version

**Comment by ottobaer** [comment] 2021-03-02 10:52
Thank you!

**Comment by darkmagas** [comment] 2021-03-02 18:22
i think the issue is fixed if you change PatchServerInfo.cs Line 56 from this : 
`ZNet.SetServerHost("", 0);`
to :
```
ZNet.ResetServerHost(); SteamManager.SetServerPort(Longship.Instance.ConfigurationManager.Configuration.ServerPort.Value);          ZSteamSocket.SetDataPort(Longship.Instance.ConfigurationManager.Configuration.ServerPort.Value);
```

i am not sure if it is working completly but i manage to run the server fine, did only a quick check on a lunch break, so probably is nto correct but hope it helps.

**Comment by kohanis** [comment] 2021-03-03 18:53
Fixed in new version

**Comment by ottobaer** [comment] 2021-03-03 19:47
Just tested it, works fine - thanks for the update!

**Closed as completed** 2021-03-03 19:47 UTC
